//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLanguages.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class About {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal About() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiLanguages.Resources.About", typeof(About).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founded 2021.
        /// </summary>
        public static string Founded {
            get {
                return ResourceManager.GetString("Founded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Company.
        /// </summary>
        public static string OurCompany {
            get {
                return ResourceManager.GetString("OurCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Expertise.
        /// </summary>
        public static string OurExpertise {
            get {
                return ResourceManager.GetString("OurExpertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our team specializes in full-stack development, including web applications, mobile apps, and cloud-based solutions. Whether you&apos;re looking for a custom software platform or a scalable app, we have the skills and experience to bring your vision to life..
        /// </summary>
        public static string OurExpertiseText {
            get {
                return ResourceManager.GetString("OurExpertiseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Mission.
        /// </summary>
        public static string OurMission {
            get {
                return ResourceManager.GetString("OurMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our mission is to empower businesses by delivering custom software solutions that drive efficiency, innovation, and growth. We combine creativity and technical expertise to ensure our clients stay ahead in today&apos;s fast-evolving digital landscape..
        /// </summary>
        public static string OurMissionText {
            get {
                return ResourceManager.GetString("OurMissionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The only way to do great work is to love what you do.&quot; - Steve Jobs.
        /// </summary>
        public static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Technology, like art, is a soaring exercise of the human imagination.&quot; - Daniel Bell.
        /// </summary>
        public static string Quote2 {
            get {
                return ResourceManager.GetString("Quote2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaping Your Vision with Technology.
        /// </summary>
        public static string Shaping {
            get {
                return ResourceManager.GetString("Shaping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At AC95, we are passionate about leveraging the latest technologies to develop cutting-edge software solutions tailored to your business needs. With a dedicated team of professionals, we help you transform your ideas into functional, scalable, and innovative software applications..
        /// </summary>
        public static string TEXT1 {
            get {
                return ResourceManager.GetString("TEXT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our focus is not only on delivering high-quality solutions, but also on fostering long-term relationships with our clients. We aim to be your trusted technology partner, helping you navigate the challenges of the digital world and achieve sustained success..
        /// </summary>
        public static string Text2 {
            get {
                return ResourceManager.GetString("Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;re looking for a partner who understands the complexities of software development and is dedicated to your success, AC95 is here to help. Let&apos;s build something amazing together..
        /// </summary>
        public static string Text3 {
            get {
                return ResourceManager.GetString("Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Choose Us?.
        /// </summary>
        public static string WhyChooseUs {
            get {
                return ResourceManager.GetString("WhyChooseUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At AC95, we pride ourselves on building strong partnerships with our clients. From concept to deployment, we collaborate closely with you to ensure we meet your unique requirements. Our agile development process ensures timely delivery, while maintaining the highest quality standards..
        /// </summary>
        public static string WhyText {
            get {
                return ResourceManager.GetString("WhyText", resourceCulture);
            }
        }
    }
}
