//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLanguages.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Design {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Design() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiLanguages.Resources.Design", typeof(Design).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Identity &amp; Logo Design.
        /// </summary>
        public static string BrandIdentityLogoDesign {
            get {
                return ResourceManager.GetString("BrandIdentityLogoDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Graphic Design Solutions.
        /// </summary>
        public static string CustomGraphicDesignSolutions {
            get {
                return ResourceManager.GetString("CustomGraphicDesignSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Services.
        /// </summary>
        public static string ExploreServices {
            get {
                return ResourceManager.GetString("ExploreServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic Design.
        /// </summary>
        public static string GraphicDesign {
            get {
                return ResourceManager.GetString("GraphicDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic Design Service.
        /// </summary>
        public static string GraphicDesignService {
            get {
                return ResourceManager.GetString("GraphicDesignService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic Design.
        /// </summary>
        public static string GraphicDesignTitle {
            get {
                return ResourceManager.GetString("GraphicDesignTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innovative.
        /// </summary>
        public static string Innovative {
            get {
                return ResourceManager.GetString("Innovative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing &amp; Advertising Design.
        /// </summary>
        public static string MarketingAdvertisingDesign {
            get {
                return ResourceManager.GetString("MarketingAdvertisingDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our.
        /// </summary>
        public static string Our {
            get {
                return ResourceManager.GetString("Our", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media Graphics.
        /// </summary>
        public static string SocialMediaGraphics {
            get {
                return ResourceManager.GetString("SocialMediaGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions for .
        /// </summary>
        public static string Solutionsfor {
            get {
                return ResourceManager.GetString("Solutionsfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Your Design Project.
        /// </summary>
        public static string StartYourDesignProject {
            get {
                return ResourceManager.GetString("StartYourDesignProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At AC95, we provide versatile graphic design solutions tailored to the unique needs of your business. From brand identity creation to social media graphics, we help your brand stand out with impactful visuals. Whether you&apos;re launching a new brand or need a fresh look for your marketing materials, we&apos;ve got you covered..
        /// </summary>
        public static string Text1 {
            get {
                return ResourceManager.GetString("Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a memorable brand identity with a custom-designed logo and brand assets. Our team works closely with you to ensure your brand&apos;s vision is captured perfectly, offering comprehensive branding packages that include logos, color schemes, typography, and more..
        /// </summary>
        public static string Text2 {
            get {
                return ResourceManager.GetString("Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our design team can create eye-catching marketing materials, including flyers, brochures, posters, and digital advertisements. Whether you&apos;re promoting a new product or running a marketing campaign, we provide designs that engage your target audience and drive results..
        /// </summary>
        public static string Text3 {
            get {
                return ResourceManager.GetString("Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhance your online presence with custom graphics for all social media platforms. From Instagram posts and stories to Facebook banners and LinkedIn ads, we provide creative visuals that align with your brand and captivate your followers..
        /// </summary>
        public static string Text4 {
            get {
                return ResourceManager.GetString("Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you need something more tailored, we offer custom graphic design services to meet your unique business needs. Whether it&apos;s packaging, event banners, or specialized promotional materials, we are here to bring your ideas to life with professional and creative solutions..
        /// </summary>
        public static string Text5 {
            get {
                return ResourceManager.GetString("Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Business.
        /// </summary>
        public static string YourBusiness {
            get {
                return ResourceManager.GetString("YourBusiness", resourceCulture);
            }
        }
    }
}
