//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLanguages.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiLanguages.Resources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC95&apos;s ability to update and maintain our online store has been crucial for our growth. Their proactive approach and tailored solutions are exactly what we needed..
        /// </summary>
        public static string Ac95ability {
            get {
                return ResourceManager.GetString("Ac95ability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC95 transformed our email marketing strategy. Their designs and personalized segmentation have doubled our open and conversion rates. Outstanding!.
        /// </summary>
        public static string AC95Transformed {
            get {
                return ResourceManager.GetString("AC95Transformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and Development.
        /// </summary>
        public static string AndDev {
            get {
                return ResourceManager.GetString("AndDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Development.
        /// </summary>
        public static string AppDev {
            get {
                return ResourceManager.GetString("AppDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at Your.
        /// </summary>
        public static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At AC95, we understand that every business is unique and deserves design solutions tailored to its specific needs. That&apos;s why we offer total flexibility, whether you need a monthly membership or one-off services. From website design to email campaign creatives and stunning graphics, our studio is equipped to be your ongoing creative partner or your project-based resource. Explore our options and discover how we can help your business stand out and thrive in the digital world..
        /// </summary>
        public static string AtAC95 {
            get {
                return ResourceManager.GetString("AtAC95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At AC95, we provide comprehensive, tailored solutions to meet all your business needs at an efficient cost. From website maintenance to email marketing campaign design, our monthly plans are crafted to perfectly fit your requirements, ensuring quality and consistency in every project..
        /// </summary>
        public static string AtAC95Month {
            get {
                return ResourceManager.GetString("AtAC95Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boost your brand with custom digital marketing, optimized for engagement and conversions..
        /// </summary>
        public static string BoostYourBrand {
            get {
                return ResourceManager.GetString("BoostYourBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build unique websites that reflect your brand and connect with visitors..
        /// </summary>
        public static string BuildUnique {
            get {
                return ResourceManager.GetString("BuildUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business&apos;s .
        /// </summary>
        public static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business..
        /// </summary>
        public static string Business2 {
            get {
                return ResourceManager.GetString("Business2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chloe W.
        /// </summary>
        public static string Chloe {
            get {
                return ResourceManager.GetString("Chloe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the service and a pre-designed template from our catalog..
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10-Apr-24.
        /// </summary>
        public static string date1 {
            get {
                return ResourceManager.GetString("date1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20-Mar-24.
        /// </summary>
        public static string date2 {
            get {
                return ResourceManager.GetString("date2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David P.
        /// </summary>
        public static string David {
            get {
                return ResourceManager.GetString("David", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define:.
        /// </summary>
        public static string Define {
            get {
                return ResourceManager.GetString("Define", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delivering.
        /// </summary>
        public static string Delivering {
            get {
                return ResourceManager.GetString("Delivering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Develop efficient online stores to boost sales and streamline product management..
        /// </summary>
        public static string DevEff {
            get {
                return ResourceManager.GetString("DevEff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Innovation .
        /// </summary>
        public static string Digital {
            get {
                return ResourceManager.GetString("Digital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Marketing.
        /// </summary>
        public static string DigitalMarketing {
            get {
                return ResourceManager.GetString("DigitalMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover How It Works:.
        /// </summary>
        public static string Discover {
            get {
                return ResourceManager.GetString("Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easily.
        /// </summary>
        public static string Easily {
            get {
                return ResourceManager.GetString("Easily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecommerce.
        /// </summary>
        public static string Ecommerce {
            get {
                return ResourceManager.GetString("Ecommerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Store Maintenance.
        /// </summary>
        public static string EcommerceMaintenance {
            get {
                return ResourceManager.GetString("EcommerceMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevate Your Business.
        /// </summary>
        public static string Elevate {
            get {
                return ResourceManager.GetString("Elevate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empower your business by hiring your own dedicated development team, tailored to your project needs for complete control and seamless collaboration..
        /// </summary>
        public static string Empower {
            get {
                return ResourceManager.GetString("Empower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTREPRENEURSHIP.
        /// </summary>
        public static string Entrepreneurship {
            get {
                return ResourceManager.GetString("Entrepreneurship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every project we&apos;ve done with AC95 has exceeded our expectations. Their team not only delivers on time but also adds value with innovative ideas and high-quality results..
        /// </summary>
        public static string EveryProject {
            get {
                return ResourceManager.GetString("EveryProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exceptional.
        /// </summary>
        public static string Exceptional {
            get {
                return ResourceManager.GetString("Exceptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Options.
        /// </summary>
        public static string Explore {
            get {
                return ResourceManager.GetString("Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore the possibilities today!.
        /// </summary>
        public static string ExplorePossibilities {
            get {
                return ResourceManager.GetString("ExplorePossibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatima Z.
        /// </summary>
        public static string Fatima {
            get {
                return ResourceManager.GetString("Fatima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Few Steps..
        /// </summary>
        public static string Few {
            get {
                return ResourceManager.GetString("Few", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill out a brief questionnaire to specify details like photos, logos, and texts..
        /// </summary>
        public static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINANCE.
        /// </summary>
        public static string Finance {
            get {
                return ResourceManager.GetString("Finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Your.
        /// </summary>
        public static string ForYour {
            get {
                return ResourceManager.GetString("ForYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get your ready-to-use design, delivered on time..
        /// </summary>
        public static string Getyour {
            get {
                return ResourceManager.GetString("Getyour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic Solution.
        /// </summary>
        public static string Graphic {
            get {
                return ResourceManager.GetString("Graphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grow and move forward..
        /// </summary>
        public static string Grow {
            get {
                return ResourceManager.GetString("Grow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hear What.
        /// </summary>
        public static string HearWhat {
            get {
                return ResourceManager.GetString("HearWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        public static string HF12 {
            get {
                return ResourceManager.GetString("HF12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Your.
        /// </summary>
        public static string Hire {
            get {
                return ResourceManager.GetString("Hire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works.
        /// </summary>
        public static string How {
            get {
                return ResourceManager.GetString("How", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideas.
        /// </summary>
        public static string Ideas {
            get {
                return ResourceManager.GetString("Ideas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I had the pleasure of working with this creative agency, and I must say, they truly impressed me. They consistently think outside the box, resulting in impressive and impactful work. I highly recommend this agency for their consistent delivery of exceptional creative solutions..
        /// </summary>
        public static string IHad {
            get {
                return ResourceManager.GetString("IHad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Just a.
        /// </summary>
        public static string Injust {
            get {
                return ResourceManager.GetString("Injust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innovative Designs.
        /// </summary>
        public static string Innovative {
            get {
                return ResourceManager.GetString("Innovative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innovative software and app development solutions designed to bring your ideas to life and deliver a seamless user experience..
        /// </summary>
        public static string InnovativeSoftware {
            get {
                return ResourceManager.GetString("InnovativeSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep your ecommerce thriving with inventory management, security updates, and ongoing technical support..
        /// </summary>
        public static string KeepYour {
            get {
                return ResourceManager.GetString("KeepYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucia M.
        /// </summary>
        public static string Lucia {
            get {
                return ResourceManager.GetString("Lucia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain peak website performance with regular updates, technical support, and SEO optimization..
        /// </summary>
        public static string Maintain {
            get {
                return ResourceManager.GetString("Maintain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Michelle L.
        /// </summary>
        public static string Michelle {
            get {
                return ResourceManager.GetString("Michelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Plans.
        /// </summary>
        public static string MonthlyPlans {
            get {
                return ResourceManager.GetString("MonthlyPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own Team.
        /// </summary>
        public static string OwnTeam {
            get {
                return ResourceManager.GetString("OwnTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Publications:.
        /// </summary>
        public static string Popular {
            get {
                return ResourceManager.GetString("Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professionals focused on helping your brand.
        /// </summary>
        public static string Professionals {
            get {
                return ResourceManager.GetString("Professionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rajesh K.
        /// </summary>
        public static string Rajesh {
            get {
                return ResourceManager.GetString("Rajesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive:.
        /// </summary>
        public static string Receive {
            get {
                return ResourceManager.GetString("Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh your branding monthly with new designs for social media, advertising, and beyond..
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results..
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select:.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since we started using AC95&apos;s design services, we&apos;ve seen a notable increase in customer engagement. Their creativity and attention to detail really make a difference..
        /// </summary>
        public static string SinceWe {
            get {
                return ResourceManager.GetString("SinceWe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software and.
        /// </summary>
        public static string Software {
            get {
                return ResourceManager.GetString("Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Creation.
        /// </summary>
        public static string StoreCreation {
            get {
                return ResourceManager.GetString("StoreCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical support and website maintenance have never been so efficient. With AC95, I truly feel we have a technological ally we can rely on..
        /// </summary>
        public static string TechnichalSupport {
            get {
                return ResourceManager.GetString("TechnichalSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting a new business can be both exciting and daunting. In this article, we share practical tips and insights to help you navigate the early stages of entrepreneurship and set your venture up for success..
        /// </summary>
        public static string Text1 {
            get {
                return ResourceManager.GetString("Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective financial management is essential for the sustainability and growth of any small business. This comprehensive guide will walk you through the best practices and tools to keep your finances in check..
        /// </summary>
        public static string Text2 {
            get {
                return ResourceManager.GetString("Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The monthly graphic design package from AC95 has been a game-changer for us. Having fresh and professional graphic resources every month effortlessly is amazing..
        /// </summary>
        public static string TheGraphic {
            get {
                return ResourceManager.GetString("TheGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They Say!.
        /// </summary>
        public static string TheySay {
            get {
                return ResourceManager.GetString("TheySay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrepreneurship 101: Practical Tips for Successfully Starting Your Business.
        /// </summary>
        public static string Title1 {
            get {
                return ResourceManager.GetString("Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Guide to Financial Management for Small Businesses.
        /// </summary>
        public static string Title2 {
            get {
                return ResourceManager.GetString("Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Together, our creative team is committed to delivering impactful work that exceeds expectations..
        /// </summary>
        public static string Together {
            get {
                return ResourceManager.GetString("Together", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique.
        /// </summary>
        public static string Unique {
            get {
                return ResourceManager.GetString("Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Plans.
        /// </summary>
        public static string ViewPlans {
            get {
                return ResourceManager.GetString("ViewPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voices:.
        /// </summary>
        public static string Voices {
            get {
                return ResourceManager.GetString("Voices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Now.
        /// </summary>
        public static string Watch {
            get {
                return ResourceManager.GetString("Watch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We.
        /// </summary>
        public static string We {
            get {
                return ResourceManager.GetString("We", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Maintenance Plan.
        /// </summary>
        public static string WebMaintenance {
            get {
                return ResourceManager.GetString("WebMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Design.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to AC95, where imagination knows no bounds and creativity brings your digital projects to life. We specialize in providing comprehensive web, graphic, and email marketing design and development solutions. Together, we will turn your visions into successful, tangible realities..
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What we do.
        /// </summary>
        public static string What {
            get {
                return ResourceManager.GetString("What", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yuto T..
        /// </summary>
        public static string Yuto {
            get {
                return ResourceManager.GetString("Yuto", resourceCulture);
            }
        }
    }
}
