//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLanguages.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HowWeWork {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HowWeWork() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiLanguages.Resources.HowWeWork", typeof(HowWeWork).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affordable.
        /// </summary>
        public static string Affordable {
            get {
                return ResourceManager.GetString("Affordable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We offer flexible monthly plans that scale with your business, providing high-quality services at affordable rates, starting from *..
        /// </summary>
        public static string AffordableText {
            get {
                return ResourceManager.GetString("AffordableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agile Developers.
        /// </summary>
        public static string Agile {
            get {
                return ResourceManager.GetString("Agile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Maintenance and Support.
        /// </summary>
        public static string AppMa {
            get {
                return ResourceManager.GetString("AppMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly maintenance and updates for your mobile app, ensuring optimal performance and security..
        /// </summary>
        public static string AppMaText {
            get {
                return ResourceManager.GetString("AppMaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approach.
        /// </summary>
        public static string Approach {
            get {
                return ResourceManager.GetString("Approach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-performance mobile and web apps that are user-friendly, secure, and scalable..
        /// </summary>
        public static string AppText {
            get {
                return ResourceManager.GetString("AppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backend Developers.
        /// </summary>
        public static string Backend {
            get {
                return ResourceManager.GetString("Backend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Website Maintenance.
        /// </summary>
        public static string BasicWeb {
            get {
                return ResourceManager.GetString("BasicWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly updates, security checks, and minor adjustments to keep your website running smoothly..
        /// </summary>
        public static string BasicWebText {
            get {
                return ResourceManager.GetString("BasicWebText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Software Development.
        /// </summary>
        public static string CustomSoftware {
            get {
                return ResourceManager.GetString("CustomSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-scale custom software development to meet the specific needs of your business..
        /// </summary>
        public static string CustomSoftwareText {
            get {
                return ResourceManager.GetString("CustomSoftwareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevOps Engineers.
        /// </summary>
        public static string DevOps {
            get {
                return ResourceManager.GetString("DevOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Marketers.
        /// </summary>
        public static string DigitalMarketers {
            get {
                return ResourceManager.GetString("DigitalMarketers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Marketing Package.
        /// </summary>
        public static string DigitalMarketingPackage {
            get {
                return ResourceManager.GetString("DigitalMarketingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehensive SEO, social media management, and content marketing to boost your online presence..
        /// </summary>
        public static string DMText {
            get {
                return ResourceManager.GetString("DMText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robust and scalable e-commerce solutions to grow your business and enhance customer experience..
        /// </summary>
        public static string EcomText {
            get {
                return ResourceManager.GetString("EcomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Services.
        /// </summary>
        public static string ExploreServices {
            get {
                return ResourceManager.GetString("ExploreServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for Your Business Growth.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontend Developers.
        /// </summary>
        public static string Frontend {
            get {
                return ResourceManager.GetString("Frontend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Stack Developers.
        /// </summary>
        public static string FullStack {
            get {
                return ResourceManager.GetString("FullStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Dedicated Teams.
        /// </summary>
        public static string Hire {
            get {
                return ResourceManager.GetString("Hire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can hire dedicated teams for software development, digital marketing, or design projects. We offer flexible hiring options, whether you need a team for a specific project, ongoing work, or sprint-based development cycles. Our teams are fully integrated into your business processes, ensuring seamless collaboration and high-quality results..
        /// </summary>
        public static string HireText {
            get {
                return ResourceManager.GetString("HireText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How We Work with You.
        /// </summary>
        public static string HowWeTitle {
            get {
                return ResourceManager.GetString("HowWeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Engagement.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Subscription Services.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our monthly subscription services provide ongoing support for website maintenance, software updates, and digital marketing campaigns. This includes performance optimizations, feature enhancements, and continuous monitoring to keep your project running smoothly..
        /// </summary>
        public static string MonthlyText {
            get {
                return ResourceManager.GetString("MonthlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire a dedicated team for ongoing development, maintenance, or design services, with flexibility to adapt to your monthly needs..
        /// </summary>
        public static string MonthText {
            get {
                return ResourceManager.GetString("MonthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our .
        /// </summary>
        public static string Our {
            get {
                return ResourceManager.GetString("Our", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Solutions.
        /// </summary>
        public static string OurSolutions {
            get {
                return ResourceManager.GetString("OurSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        public static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Owners.
        /// </summary>
        public static string ProductOwners {
            get {
                return ResourceManager.GetString("ProductOwners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project-Based Services.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Managers.
        /// </summary>
        public static string ProjectManagers {
            get {
                return ResourceManager.GetString("ProjectManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a dedicated team for a specific project, ensuring your project goals are met on time with high-quality deliverables..
        /// </summary>
        public static string ProjectServiceText {
            get {
                return ResourceManager.GetString("ProjectServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We offer project-based services across a wide range of areas, including software development, web design, and digital marketing. Whether you&apos;re looking to build a custom software solution, redesign your website, or create a digital marketing campaign, our team will deliver high-quality results tailored to your business needs..
        /// </summary>
        public static string ProjectText {
            get {
                return ResourceManager.GetString("ProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project-Based.
        /// </summary>
        public static string ProjectTitle {
            get {
                return ResourceManager.GetString("ProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA Engineers.
        /// </summary>
        public static string QA {
            get {
                return ResourceManager.GetString("QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA Testers.
        /// </summary>
        public static string QATesters {
            get {
                return ResourceManager.GetString("QATesters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum Masters.
        /// </summary>
        public static string ScrumMasters {
            get {
                return ResourceManager.GetString("ScrumMasters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Options.
        /// </summary>
        public static string ServiceOptions {
            get {
                return ResourceManager.GetString("ServiceOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom software solutions tailored to your specific business challenges and goals..
        /// </summary>
        public static string SoftText {
            get {
                return ResourceManager.GetString("SoftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint-Based Engagement.
        /// </summary>
        public static string Sprint {
            get {
                return ResourceManager.GetString("Sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engage a team to work with you on a sprint basis, perfect for agile development environments where goals are achieved incrementally..
        /// </summary>
        public static string SprintText {
            get {
                return ResourceManager.GetString("SprintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At AC95, we offer flexible ways to work with us, tailored to your project needs. Whether you’re looking for one-time project services, ongoing support, or dedicated teams, we have the right solution to help you achieve your goals..
        /// </summary>
        public static string Text1 {
            get {
                return ResourceManager.GetString("Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI/UX Designers.
        /// </summary>
        public static string UIUX {
            get {
                return ResourceManager.GetString("UIUX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom websites designed to deliver top-tier performance and engaging user experiences..
        /// </summary>
        public static string WebText {
            get {
                return ResourceManager.GetString("WebText", resourceCulture);
            }
        }
    }
}
