//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLanguages.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class monthlydesign {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal monthlydesign() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiLanguages.Resources.monthlydesign", typeof(monthlydesign).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Identity Design.
        /// </summary>
        public static string BrandIdentityDesign {
            get {
                return ResourceManager.GetString("BrandIdentityDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Graphic Design.
        /// </summary>
        public static string CustomGraphicDesign {
            get {
                return ResourceManager.GetString("CustomGraphicDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic.
        /// </summary>
        public static string Graphic {
            get {
                return ResourceManager.GetString("Graphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic Design.
        /// </summary>
        public static string GraphicDesign {
            get {
                return ResourceManager.GetString("GraphicDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic Design.
        /// </summary>
        public static string GraphicDesignS {
            get {
                return ResourceManager.GetString("GraphicDesignS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing Materials.
        /// </summary>
        public static string MarketingMaterials {
            get {
                return ResourceManager.GetString("MarketingMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string MonthlyTitle {
            get {
                return ResourceManager.GetString("MonthlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our.
        /// </summary>
        public static string Our {
            get {
                return ResourceManager.GetString("Our", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print &amp; Digital Assets.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media Graphics.
        /// </summary>
        public static string SocialMediaGraphics {
            get {
                return ResourceManager.GetString("SocialMediaGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe Now.
        /// </summary>
        public static string SubscribeNow {
            get {
                return ResourceManager.GetString("SubscribeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our graphic design subscription service provides you with ongoing design support every month. Whether you need logos, marketing materials, or social media graphics, our team delivers high-quality designs tailored to your brand..
        /// </summary>
        public static string Text1 {
            get {
                return ResourceManager.GetString("Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get custom graphic design solutions tailored to your brand&apos;s needs. From logos to business cards and product packaging, we create designs that enhance your visual identity and make a lasting impact..
        /// </summary>
        public static string Text2 {
            get {
                return ResourceManager.GetString("Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We design eye-catching marketing materials like brochures, flyers, and banners to help you promote your business. Our designs are created to grab attention and drive engagement with your audience..
        /// </summary>
        public static string Text3 {
            get {
                return ResourceManager.GetString("Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our team creates engaging social media graphics to boost your online presence. From Instagram posts to Facebook banners, we design content that aligns with your brand and engages your followers..
        /// </summary>
        public static string Text4 {
            get {
                return ResourceManager.GetString("Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We help businesses develop a strong visual identity by designing logos, color schemes, and typography that reflect your brand&apos;s personality and values. Our brand identity designs set you apart from the competition..
        /// </summary>
        public static string Text5 {
            get {
                return ResourceManager.GetString("Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From digital banners to printed materials, we provide designs that work across all formats. Whether for online ads, print campaigns, or trade show materials, we create assets that are visually stunning and effective..
        /// </summary>
        public static string Text6 {
            get {
                return ResourceManager.GetString("Text6", resourceCulture);
            }
        }
    }
}
