//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLanguages.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Monthly {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Monthly() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiLanguages.Resources.Monthly", typeof(Monthly).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Maintenance.
        /// </summary>
        public static string AppMaintenance {
            get {
                return ResourceManager.GetString("AppMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Solutions.
        /// </summary>
        public static string BrandSolutions {
            get {
                return ResourceManager.GetString("BrandSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Marketing.
        /// </summary>
        public static string DigitalMarketing {
            get {
                return ResourceManager.GetString("DigitalMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Commerce Management.
        /// </summary>
        public static string ECommerceManagement {
            get {
                return ResourceManager.GetString("ECommerceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic Design.
        /// </summary>
        public static string GraphicDesign {
            get {
                return ResourceManager.GetString("GraphicDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire a Team.
        /// </summary>
        public static string HireaTeam {
            get {
                return ResourceManager.GetString("HireaTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string MonthlyCat {
            get {
                return ResourceManager.GetString("MonthlyCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string MonthlyTitle {
            get {
                return ResourceManager.GetString("MonthlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        public static string PlanTitle {
            get {
                return ResourceManager.GetString("PlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services categories:.
        /// </summary>
        public static string Servicescategories {
            get {
                return ResourceManager.GetString("Servicescategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string ServicesTitle {
            get {
                return ResourceManager.GetString("ServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Development.
        /// </summary>
        public static string SoftwareDevelopment {
            get {
                return ResourceManager.GetString("SoftwareDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep your website running smoothly with our monthly web maintenance service. We ensure regular updates, performance optimization, and security checks to provide your users with a seamless experience..
        /// </summary>
        public static string Text1 {
            get {
                return ResourceManager.GetString("Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our e-commerce management service ensures your online store operates efficiently. We handle product updates, order management, and inventory tracking, so you can focus on growing your business..
        /// </summary>
        public static string Text2 {
            get {
                return ResourceManager.GetString("Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep your app functioning at its best with our app maintenance service. We provide updates, bug fixes, and performance enhancements to ensure your app remains stable and up to date..
        /// </summary>
        public static string Text3 {
            get {
                return ResourceManager.GetString("Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From concept to deployment, our monthly software development service offers continuous support for your projects. We help you build, test, and refine software tailored to your specific needs..
        /// </summary>
        public static string Text4 {
            get {
                return ResourceManager.GetString("Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our monthly digital marketing service helps you grow your online presence through tailored strategies. From social media management to SEO and paid ads, we ensure that your business stays competitive and visible online..
        /// </summary>
        public static string Text5 {
            get {
                return ResourceManager.GetString("Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our monthly graphic design service provides you with ongoing design support. Whether you need logos, marketing materials, or social media graphics, our team delivers high-quality designs tailored to your brand..
        /// </summary>
        public static string Text6 {
            get {
                return ResourceManager.GetString("Text6", resourceCulture);
            }
        }
    }
}
