//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLanguages.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Monthlymarketing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Monthlymarketing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiLanguages.Resources.Monthlymarketing", typeof(Monthlymarketing).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics &amp; Reporting.
        /// </summary>
        public static string Analytics {
            get {
                return ResourceManager.GetString("Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Marketing.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Marketing.
        /// </summary>
        public static string Digital_Marketing {
            get {
                return ResourceManager.GetString("Digital Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Marketing.
        /// </summary>
        public static string DigitalMarketing {
            get {
                return ResourceManager.GetString("DigitalMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Marketing.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our.
        /// </summary>
        public static string Our {
            get {
                return ResourceManager.GetString("Our", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay-Per-Click Advertising (PPC).
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Engine Optimization (SEO).
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media Management.
        /// </summary>
        public static string SocialMediaManagement {
            get {
                return ResourceManager.GetString("SocialMediaManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With our digital marketing subscription service, we help you grow your online presence through consistent marketing strategies. From social media management to SEO and paid ads, we work to achieve your business goals month after month..
        /// </summary>
        public static string Text1 {
            get {
                return ResourceManager.GetString("Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We manage your social media platforms, creating and scheduling content that engages your audience and builds brand awareness. Our team ensures your social media presence remains active and aligned with your marketing goals..
        /// </summary>
        public static string Text2 {
            get {
                return ResourceManager.GetString("Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our SEO services focus on improving your website&apos;s ranking in search engines. We work on on-page and off-page SEO strategies to drive organic traffic to your website, ensuring long-term growth and visibility..
        /// </summary>
        public static string Text3 {
            get {
                return ResourceManager.GetString("Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We create and manage PPC campaigns on platforms like Google Ads and social media. Our team optimizes ad copy, targeting, and bidding strategies to maximize your return on investment and generate qualified leads..
        /// </summary>
        public static string Text4 {
            get {
                return ResourceManager.GetString("Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We produce valuable content that resonates with your audience, from blog posts and articles to infographics and videos. Our content marketing strategy focuses on building trust with your audience and driving engagement..
        /// </summary>
        public static string Text5 {
            get {
                return ResourceManager.GetString("Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our email marketing service helps you maintain contact with your audience through well-crafted email campaigns. We design and execute strategies that drive conversions, increase customer retention, and build lasting relationships..
        /// </summary>
        public static string Text6 {
            get {
                return ResourceManager.GetString("Text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We provide monthly reports with detailed insights into your marketing performance. From traffic sources to conversion rates, we analyze the data to continually refine and improve your digital marketing efforts..
        /// </summary>
        public static string Text7 {
            get {
                return ResourceManager.GetString("Text7", resourceCulture);
            }
        }
    }
}
