//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLanguages.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiLanguages.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Innovation.
        /// </summary>
        public static string HA1 {
            get {
                return ResourceManager.GetString("HA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at Your.
        /// </summary>
        public static string HA2 {
            get {
                return ResourceManager.GetString("HA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business&apos;s .
        /// </summary>
        public static string HA3 {
            get {
                return ResourceManager.GetString("HA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string HA4 {
            get {
                return ResourceManager.GetString("HA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to AC95, where imagination knows no bounds and creativity brings your digital projects to life. We specialize in providing comprehensive web, graphic, and email marketing design and development solutions. Together, we will turn your visions into successful, tangible realities..
        /// </summary>
        public static string HA5 {
            get {
                return ResourceManager.GetString("HA5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What we do.
        /// </summary>
        public static string HA6 {
            get {
                return ResourceManager.GetString("HA6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works.
        /// </summary>
        public static string HA7 {
            get {
                return ResourceManager.GetString("HA7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innovative Designs.
        /// </summary>
        public static string HB1 {
            get {
                return ResourceManager.GetString("HB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the service and a pre-designed template from our catalog..
        /// </summary>
        public static string HB10 {
            get {
                return ResourceManager.GetString("HB10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define:.
        /// </summary>
        public static string HB11 {
            get {
                return ResourceManager.GetString("HB11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill out a brief questionnaire to specify details like photos, logos, and texts..
        /// </summary>
        public static string HB12 {
            get {
                return ResourceManager.GetString("HB12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive:.
        /// </summary>
        public static string HB13 {
            get {
                return ResourceManager.GetString("HB13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get your ready-to-use design, delivered on time..
        /// </summary>
        public static string HB14 {
            get {
                return ResourceManager.GetString("HB14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover How It Works:.
        /// </summary>
        public static string HB15 {
            get {
                return ResourceManager.GetString("HB15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Now.
        /// </summary>
        public static string HB16 {
            get {
                return ResourceManager.GetString("HB16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string HB2 {
            get {
                return ResourceManager.GetString("HB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevate Your Business.
        /// </summary>
        public static string HB3 {
            get {
                return ResourceManager.GetString("HB3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At AC95, we understand that every business is unique and deserves design solutions tailored to its specific needs. That&apos;s why we offer total flexibility, whether you need a monthly membership or one-off services. From website design to email campaign creatives and stunning graphics, our studio is equipped to be your ongoing creative partner or your project-based resource. Explore our options and discover how we can help your business stand out and thrive in the digital world..
        /// </summary>
        public static string HB4 {
            get {
                return ResourceManager.GetString("HB4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string HB5 {
            get {
                return ResourceManager.GetString("HB5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easily.
        /// </summary>
        public static string HB6 {
            get {
                return ResourceManager.GetString("HB6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Just a.
        /// </summary>
        public static string HB7 {
            get {
                return ResourceManager.GetString("HB7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Few Steps..
        /// </summary>
        public static string HB8 {
            get {
                return ResourceManager.GetString("HB8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select:.
        /// </summary>
        public static string HB9 {
            get {
                return ResourceManager.GetString("HB9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professionals focused on helping your brand.
        /// </summary>
        public static string HC1 {
            get {
                return ResourceManager.GetString("HC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecommerce.
        /// </summary>
        public static string HC10 {
            get {
                return ResourceManager.GetString("HC10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Creation.
        /// </summary>
        public static string HC11 {
            get {
                return ResourceManager.GetString("HC11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Develop efficient online stores to boost sales and streamline product management..
        /// </summary>
        public static string HC12 {
            get {
                return ResourceManager.GetString("HC12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software and.
        /// </summary>
        public static string HC13 {
            get {
                return ResourceManager.GetString("HC13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Development.
        /// </summary>
        public static string HC14 {
            get {
                return ResourceManager.GetString("HC14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innovative software and app development solutions designed to bring your ideas to life and deliver a seamless user experience..
        /// </summary>
        public static string HC15 {
            get {
                return ResourceManager.GetString("HC15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Your.
        /// </summary>
        public static string HC16 {
            get {
                return ResourceManager.GetString("HC16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own Team.
        /// </summary>
        public static string HC17 {
            get {
                return ResourceManager.GetString("HC17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empower your business by hiring your own dedicated development team, tailored to your project needs for complete control and seamless collaboration..
        /// </summary>
        public static string HC18 {
            get {
                return ResourceManager.GetString("HC18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grow and move forward..
        /// </summary>
        public static string HC2 {
            get {
                return ResourceManager.GetString("HC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique.
        /// </summary>
        public static string HC3 {
            get {
                return ResourceManager.GetString("HC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideas.
        /// </summary>
        public static string HC4 {
            get {
                return ResourceManager.GetString("HC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Your.
        /// </summary>
        public static string HC41 {
            get {
                return ResourceManager.GetString("HC41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business..
        /// </summary>
        public static string HC5 {
            get {
                return ResourceManager.GetString("HC5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What we do.
        /// </summary>
        public static string HC6 {
            get {
                return ResourceManager.GetString("HC6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Design.
        /// </summary>
        public static string HC7 {
            get {
                return ResourceManager.GetString("HC7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and Development.
        /// </summary>
        public static string HC8 {
            get {
                return ResourceManager.GetString("HC8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build unique websites that reflect your brand and connect with visitors..
        /// </summary>
        public static string HC9 {
            get {
                return ResourceManager.GetString("HC9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string HD1 {
            get {
                return ResourceManager.GetString("HD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Maintenance Plan.
        /// </summary>
        public static string HD10 {
            get {
                return ResourceManager.GetString("HD10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain peak website performance with regular updates, technical support, and SEO optimization..
        /// </summary>
        public static string HD11 {
            get {
                return ResourceManager.GetString("HD11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Options.
        /// </summary>
        public static string HD12 {
            get {
                return ResourceManager.GetString("HD12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Store Maintenance.
        /// </summary>
        public static string HD13 {
            get {
                return ResourceManager.GetString("HD13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep your ecommerce thriving with inventory management, security updates, and ongoing technical support..
        /// </summary>
        public static string HD14 {
            get {
                return ResourceManager.GetString("HD14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Options.
        /// </summary>
        public static string HD15 {
            get {
                return ResourceManager.GetString("HD15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore the possibilities today!.
        /// </summary>
        public static string HD16 {
            get {
                return ResourceManager.GetString("HD16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic Solution.
        /// </summary>
        public static string HD17 {
            get {
                return ResourceManager.GetString("HD17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh your branding monthly with new designs for social media, advertising, and beyond..
        /// </summary>
        public static string HD18 {
            get {
                return ResourceManager.GetString("HD18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Options.
        /// </summary>
        public static string HD19 {
            get {
                return ResourceManager.GetString("HD19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Plans.
        /// </summary>
        public static string HD2 {
            get {
                return ResourceManager.GetString("HD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Marketing Design.
        /// </summary>
        public static string HD20 {
            get {
                return ResourceManager.GetString("HD20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhance your email campaigns with custom designs, optimized for engagement and conversion, perfect for newsletters, promotions, and more..
        /// </summary>
        public static string HD21 {
            get {
                return ResourceManager.GetString("HD21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Options.
        /// </summary>
        public static string HD22 {
            get {
                return ResourceManager.GetString("HD22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At AC95, we provide comprehensive, tailored solutions to meet all your business needs at an efficient cost. From website maintenance to email marketing campaign design, our monthly plans are crafted to perfectly fit your requirements, ensuring quality and consistency in every project..
        /// </summary>
        public static string HD3 {
            get {
                return ResourceManager.GetString("HD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Together, our creative team is committed to delivering impactful work that exceeds expectations..
        /// </summary>
        public static string HD4 {
            get {
                return ResourceManager.GetString("HD4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Plans.
        /// </summary>
        public static string HD5 {
            get {
                return ResourceManager.GetString("HD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We.
        /// </summary>
        public static string HD6 {
            get {
                return ResourceManager.GetString("HD6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delivering.
        /// </summary>
        public static string HD7 {
            get {
                return ResourceManager.GetString("HD7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exceptional.
        /// </summary>
        public static string HD8 {
            get {
                return ResourceManager.GetString("HD8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results..
        /// </summary>
        public static string HD9 {
            get {
                return ResourceManager.GetString("HD9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string HE1 {
            get {
                return ResourceManager.GetString("HE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical support and website maintenance have never been so efficient. With AC95, I truly feel we have a technological ally we can rely on..
        /// </summary>
        public static string HE10 {
            get {
                return ResourceManager.GetString("HE10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chloe W.
        /// </summary>
        public static string HE11 {
            get {
                return ResourceManager.GetString("HE11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC95 transformed our email marketing strategy. Their designs and personalized segmentation have doubled our open and conversion rates. Outstanding!.
        /// </summary>
        public static string HE12 {
            get {
                return ResourceManager.GetString("HE12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yuto T..
        /// </summary>
        public static string HE13 {
            get {
                return ResourceManager.GetString("HE13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC95&apos;s ability to update and maintain our online store has been crucial for our growth. Their proactive approach and tailored solutions are exactly what we needed..
        /// </summary>
        public static string HE14 {
            get {
                return ResourceManager.GetString("HE14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatima Z.
        /// </summary>
        public static string HE15 {
            get {
                return ResourceManager.GetString("HE15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every project we&apos;ve done with AC95 has exceeded our expectations. Their team not only delivers on time but also adds value with innovative ideas and high-quality results..
        /// </summary>
        public static string HE16 {
            get {
                return ResourceManager.GetString("HE16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David P.
        /// </summary>
        public static string HE17 {
            get {
                return ResourceManager.GetString("HE17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The monthly graphic design package from AC95 has been a game-changer for us. Having fresh and professional graphic resources every month effortlessly is amazing..
        /// </summary>
        public static string HE18 {
            get {
                return ResourceManager.GetString("HE18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voices:.
        /// </summary>
        public static string HE2 {
            get {
                return ResourceManager.GetString("HE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hear What.
        /// </summary>
        public static string HE3 {
            get {
                return ResourceManager.GetString("HE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They Say!.
        /// </summary>
        public static string HE4 {
            get {
                return ResourceManager.GetString("HE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Michelle L.
        /// </summary>
        public static string HE5 {
            get {
                return ResourceManager.GetString("HE5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since we started using AC95&apos;s design services, we&apos;ve seen a notable increase in customer engagement. Their creativity and attention to detail really make a difference..
        /// </summary>
        public static string HE6 {
            get {
                return ResourceManager.GetString("HE6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucia M.
        /// </summary>
        public static string HE7 {
            get {
                return ResourceManager.GetString("HE7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I had the pleasure of working with this creative agency, and I must say, they truly impressed me. They consistently think outside the box, resulting in impressive and impactful work. I highly recommend this agency for their consistent delivery of exceptional creative solutions..
        /// </summary>
        public static string HE8 {
            get {
                return ResourceManager.GetString("HE8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rajesh K.
        /// </summary>
        public static string HE9 {
            get {
                return ResourceManager.GetString("HE9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Publications:.
        /// </summary>
        public static string HF1 {
            get {
                return ResourceManager.GetString("HF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Guide to Financial Management for Small Businesses.
        /// </summary>
        public static string HF10 {
            get {
                return ResourceManager.GetString("HF10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective financial management is essential for the sustainability and growth of any small business. This comprehensive guide will walk you through the best practices and tools to keep your finances in check..
        /// </summary>
        public static string HF11 {
            get {
                return ResourceManager.GetString("HF11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        public static string HF12 {
            get {
                return ResourceManager.GetString("HF12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        public static string HF2 {
            get {
                return ResourceManager.GetString("HF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTREPRENEURSHIP.
        /// </summary>
        public static string HF3 {
            get {
                return ResourceManager.GetString("HF3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10-Apr-24.
        /// </summary>
        public static string HF4 {
            get {
                return ResourceManager.GetString("HF4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrepreneurship 101: Practical Tips for Successfully Starting Your Business.
        /// </summary>
        public static string HF5 {
            get {
                return ResourceManager.GetString("HF5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting a new business can be both exciting and daunting. In this article, we share practical tips and insights to help you navigate the early stages of entrepreneurship and set your venture up for success..
        /// </summary>
        public static string HF6 {
            get {
                return ResourceManager.GetString("HF6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        public static string HF7 {
            get {
                return ResourceManager.GetString("HF7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINANCE.
        /// </summary>
        public static string HF8 {
            get {
                return ResourceManager.GetString("HF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20-Mar-24.
        /// </summary>
        public static string HF9 {
            get {
                return ResourceManager.GetString("HF9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string M1 {
            get {
                return ResourceManager.GetString("M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Solutions.
        /// </summary>
        public static string M10 {
            get {
                return ResourceManager.GetString("M10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoftwareDevelopment.
        /// </summary>
        public static string M11 {
            get {
                return ResourceManager.GetString("M11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Developtment.
        /// </summary>
        public static string M12 {
            get {
                return ResourceManager.GetString("M12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Development.
        /// </summary>
        public static string M13 {
            get {
                return ResourceManager.GetString("M13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Commerce Stores.
        /// </summary>
        public static string M14 {
            get {
                return ResourceManager.GetString("M14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic Design.
        /// </summary>
        public static string M15 {
            get {
                return ResourceManager.GetString("M15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Marketing.
        /// </summary>
        public static string M16 {
            get {
                return ResourceManager.GetString("M16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful links.
        /// </summary>
        public static string M17 {
            get {
                return ResourceManager.GetString("M17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string M18 {
            get {
                return ResourceManager.GetString("M18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        public static string M19 {
            get {
                return ResourceManager.GetString("M19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string M2 {
            get {
                return ResourceManager.GetString("M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie Policy.
        /// </summary>
        public static string M20 {
            get {
                return ResourceManager.GetString("M20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careers.
        /// </summary>
        public static string M21 {
            get {
                return ResourceManager.GetString("M21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA.
        /// </summary>
        public static string M22 {
            get {
                return ResourceManager.GetString("M22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How We Work.
        /// </summary>
        public static string M3 {
            get {
                return ResourceManager.GetString("M3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Solutions.
        /// </summary>
        public static string M4 {
            get {
                return ResourceManager.GetString("M4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Plan.
        /// </summary>
        public static string M5 {
            get {
                return ResourceManager.GetString("M5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Your Own Team.
        /// </summary>
        public static string M6 {
            get {
                return ResourceManager.GetString("M6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Solutions.
        /// </summary>
        public static string M7 {
            get {
                return ResourceManager.GetString("M7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        public static string M8 {
            get {
                return ResourceManager.GetString("M8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string M9 {
            get {
                return ResourceManager.GetString("M9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string P1 {
            get {
                return ResourceManager.GetString("P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string P2 {
            get {
                return ResourceManager.GetString("P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
    }
}
