//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLanguages.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Team {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Team() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiLanguages.Resources.Team", typeof(Team).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Suite of Roles.
        /// </summary>
        public static string FullSuiteofRoles {
            get {
                return ResourceManager.GetString("FullSuiteofRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started Now.
        /// </summary>
        public static string GetStartedNow {
            get {
                return ResourceManager.GetString("GetStartedNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire a Team.
        /// </summary>
        public static string Hire {
            get {
                return ResourceManager.GetString("Hire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire by Project.
        /// </summary>
        public static string HirebyProject {
            get {
                return ResourceManager.GetString("HirebyProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire by Sprint.
        /// </summary>
        public static string HirebySprint {
            get {
                return ResourceManager.GetString("HirebySprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire by the Month.
        /// </summary>
        public static string HirebytheMonth {
            get {
                return ResourceManager.GetString("HirebytheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Your Own.
        /// </summary>
        public static string HireYourOwn {
            get {
                return ResourceManager.GetString("HireYourOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        public static string on {
            get {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEAM HIRING.
        /// </summary>
        public static string TEAMHIRING {
            get {
                return ResourceManager.GetString("TEAMHIRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a dedicated team of professionals such as developers, project managers, or scrum masters to support your business on a monthly basis. Ideal for ongoing projects or continuous development needs..
        /// </summary>
        public static string Text1 {
            get {
                return ResourceManager.GetString("Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemble a team for a specific project. Whether you&apos;re developing software, launching a web platform, or executing a marketing strategy, we provide the exact roles you need to ensure project success..
        /// </summary>
        public static string Text2 {
            get {
                return ResourceManager.GetString("Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the flexibility of sprint-based hiring. Scale your team during critical development phases or agile sprints with developers, designers, or agile coaches who are experts in getting things done fast..
        /// </summary>
        public static string Text3 {
            get {
                return ResourceManager.GetString("Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access a wide range of skilled professionals for your team including developers, project managers, scrum masters, designers, and more. Tailor the team to fit your specific business requirements..
        /// </summary>
        public static string Text4 {
            get {
                return ResourceManager.GetString("Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Terms.
        /// </summary>
        public static string YourTerms {
            get {
                return ResourceManager.GetString("YourTerms", resourceCulture);
            }
        }
    }
}
