//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLanguages.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Web {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Web() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiLanguages.Resources.Web", typeof(Web).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Integration.
        /// </summary>
        public static string AIIntegration {
            get {
                return ResourceManager.GetString("AIIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating .
        /// </summary>
        public static string Creating {
            get {
                return ResourceManager.GetString("Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Website Development.
        /// </summary>
        public static string CustomWeb {
            get {
                return ResourceManager.GetString("CustomWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our .
        /// </summary>
        public static string Our {
            get {
                return ResourceManager.GetString("Our", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Optimization.
        /// </summary>
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsive Design.
        /// </summary>
        public static string ResponsiveDesign {
            get {
                return ResourceManager.GetString("ResponsiveDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO Optimization.
        /// </summary>
        public static string SEO {
            get {
                return ResourceManager.GetString("SEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Your Project.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At AC95, we specialize in creating websites that combine design, performance, and user experience. Whether you need a basic website or a complex solution, our team delivers tailored websites to elevate your online presence..
        /// </summary>
        public static string Text1 {
            get {
                return ResourceManager.GetString("Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We build websites from the ground up, tailored to your brand and business goals. Our websites are designed to engage users, enhance performance, and offer a seamless user experience across all devices..
        /// </summary>
        public static string Text2 {
            get {
                return ResourceManager.GetString("Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our websites are built with responsive design, ensuring they look and perform perfectly across all screen sizes, from desktop to mobile. We prioritize usability and speed, offering the best experience for your visitors..
        /// </summary>
        public static string Text3 {
            get {
                return ResourceManager.GetString("Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep your website running smoothly with our ongoing maintenance services. We handle security updates, performance optimizations, and content updates to ensure your site remains up-to-date and fully functional..
        /// </summary>
        public static string Text4 {
            get {
                return ResourceManager.GetString("Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our websites are built with search engine optimization (SEO) best practices, ensuring your website ranks higher in search results and attracts more organic traffic. We focus on page speed, mobile usability, meta tags, and clean code to improve your SEO performance..
        /// </summary>
        public static string Text5 {
            get {
                return ResourceManager.GetString("Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We offer seamless AI integration to enhance your website with automation, data analysis, and personalized experiences. Our AI solutions optimize user interaction, improve efficiency, and help your business grow intelligently..
        /// </summary>
        public static string Text6 {
            get {
                return ResourceManager.GetString("Text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We optimize your website for fast loading times and efficient performance. Our optimization techniques ensure your site loads quickly across all devices, reducing bounce rates and improving user engagement..
        /// </summary>
        public static string Text7 {
            get {
                return ResourceManager.GetString("Text7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string titleweb {
            get {
                return ResourceManager.GetString("titleweb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Maintenance.
        /// </summary>
        public static string WebsiteMaintenance {
            get {
                return ResourceManager.GetString("WebsiteMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Websites for .
        /// </summary>
        public static string Websites {
            get {
                return ResourceManager.GetString("Websites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Business.
        /// </summary>
        public static string YourBusiness {
            get {
                return ResourceManager.GetString("YourBusiness", resourceCulture);
            }
        }
    }
}
